### ISSUE TITLE
Question :)

### ISSUE THREAD

**Issue by sosafe-uliana** [muchzill4/retros-against-humanity#1]
Hello dear friend!
I have forked your beautiful project to set up an extended version for my team. Trying to deploy it to gh-pages doesn't work out for me though. Could you share with me how you made it work? I don't have much experience with it.

**Comment by muchzill4** [comment]
Hi @sosafe-uliana,

Thanks for kind words. 

The deployment to GitHub Pages is done via the [`deploy-gh-pages.yml`](https://github.com/muchzill4/retros-against-humanity/blob/master/.github/workflows/deploy-gh-pages.yml) workflow in the repo. As far as I can tell, your fork contains it too. It should run on every push to `master`. 
I see you've also added a new workflow file called `static.yml`. That's not required and should be removed - `deploy-gh-pages.yml` should be enough.

It might be that you need to configure pages on your fork repository settings. See how it is done here:
<img width="1125" alt="Screenshot 2024-09-27 at 12 01 28" src="https://github.com/user-attachments/assets/e06b761a-37f3-44bf-88c1-81e3e1debdc6">

Hope your team likes the retro format. 👍

**Comment by sosafe-uliana** [comment]
Ahhh i got it, thank you! what I was missing was to switch the branch to `gh-pages`.
